### ISSUE TITLE
Unaccounted Transactions

### ISSUE THREAD

**Issue by bennesp** [lorenzogiudici5/ofxstatement-hype#2]
Currently, when 'Data Contabile' is null, the system defaults to using 'Data Operazione' as 'Data Contabile'. This approach can lead to inaccuracies in financial reporting.

Instead, transactions with a null 'Data Contabile' should be ignored to ensure the correctness of our transaction records.

Other ofxstatement plugins follow this practice (eg: ofxstatement-intesasp)

This becomes a real problem with rejected transactions, since these are reported in the exported PDF but, obviously, being rejected, they should not be accounted

**Comment by lorenzogiudici5** [comment]
You're right @bennesp: I haven't got similar cases so I didn't think too much that no "Data Contabile" simply means rejected transaction and should be ignored.
Thanks for the issue and the PR!

**Comment by lorenzogiudici5** [comment]
@bennesp are you sure that rejected transactions are listed in pdf? This month I had rejected transactions but they are not present in my pdf report.

Then, I have a "Data Contabile" null case. I made a **successful** payment on 31 July and on 1 Aug I downloaded my pdf report: this operation has "Data Contabile" null (simply because it has been settled on 2 Aug).

**Comment by bennesp** [comment]
This does not happen for generic rejected transactions (eg: due to insufficient funds).

This happened to me for some (successful) transactions that were contested afterwards because the card was cloned and used by someone else. As such, the bank proceeded to avoid the accounting of those transactions, but kept them for some reason in the export.

See the image attached

<img width="711" alt="Screenshot 2024-08-06 alle 10 19 02" src="https://github.com/user-attachments/assets/9ee2a8cf-2582-413c-abc3-6ccaafb7138a">

**Comment by bennesp** [comment]
My 2 cents: in any case, I see the practice also in other integrations systems (like gocardless) to completely ignore not yet accounted transactions to avoid having to deal with these issues. In fact, a transaction is effectively there when the bank says it's accounted, at least to me
